stages:
  - name: Maven Compile
    steps:
      - runScriptConfig:
          image: maven:3.6.0-jdk-8
          shellScript: |-
            mvn clean package  --settings ./maven-settings.xml -Dmaven.test.skip=true
  - name: Docker Build
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: ccr.ccs.tencentyun.com/efashion-cloud/cloud-tracking-service:${CICD_GIT_BRANCH}-build-${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: ccr.ccs.tencentyun.com
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment-${CICD_GIT_BRANCH}.yaml
timeout: 60
branch:
  include:
    - develop
    - master
notification:
  recipients:
    - recipient: cloud@efashionchina.com
      notifier: c-kd7kp:n-4vnmm
  condition:
    - Success
    - Failed
