apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-service-staging-cloud-tracking-service
  name: cloud-tracking-service
  namespace: service-staging
spec:
  minReadySeconds: 120
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-service-staging-cloud-tracking-service
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-service-staging-cloud-tracking-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: cloud-service-map
                optional: false
          image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-build-${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          name: cloud-tracking-service
          resources: {}
      imagePullSecrets:
        - name: efashion
